language: cpp

compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -q
  - sudo apt-get install -y libfreeimage-dev libassimp-dev libboost1.55-dev libboost-filesystem1.55-dev libboost-program-options1.55-dev libboost-regex1.55-dev 

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make

