language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libfreeimage-dev libassimp-dev

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make

