language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost1.53-dev libboost-filesystem1.53-dev libboost-program-options1.53-dev libboost-regex1.53-dev libfreeimage1.53-dev libassimp1.53-dev

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make

