branches:
  only:
    - master
  except:
    - gh-pages

clone_folder: c:\projects\lightmetrica

environment:
  BOOST_INCLUDEDIR: c:\Libraries\boost
  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib

before_build:
  - git submodule init
  - git submodule update

build_script:
  - cd c:\Libraries\boost
  - dir
  - cd c:\Libraries\boost\stage
  - dir
  - cd c:\projects\lightmetrica
  - md build
  - cd build
  - cmake -G "Visual Studio 12 Win64" ..
  - msbuild /m /p:Configuration=Release /p:Platform=x64 lightmetrica.sln

test_script:
  - ps: cd bin\Release
  - ps: lightmetrica.test.exe
